language: python
virtualenv:
  system_site_packages: true
python:
- 3.6
- 3.5
- 3.4
- 2.7
before_install:
  - sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get -qq update
  - sudo apt-get install gdal-bin -y
  - sudo apt-get install libgdal-dev -y
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - sudo apt-get install python-gdal
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: giswqs
  password:
    secure: LMVKQOp+5Bj9HpMlMnNxm3nRmAxw7dqZ/WgnB7zSwwQakXGAswk+FvuIs6w7EBgU2CnTIlNb/bJURbFGIEpErQ/2sVkNppdOWqP31KEeZ/ajB82dyXcgvOPq5IztYPPJKVLWPCU+uxi2PR+2JBt4/NQxhp6DLJrXHGckgyOH5nCO1UlANOOFC3D6UxY7MY0k/DnF7OdzH1c7lwd8EyVLk4T5Vlhoy+w6YoBgvOO3bydiUEj6HPSFSQnXc/u/T95F1HZGGz/WoOplDP6RVDQ9/htg2EbkObYJD+MnmLRnse9N3Hjpq/FXqicMYi1Vmr1ysxAaAv88nDvZw347vyS4qYClaSSVGBV2/ks45D2ewo0QptCvo/uU1PSVV20EKWYRe31sejhe2o8XZ6t3ULZSbfUOVYMrKpF1yarse885TyaH1+ZOs0o9AT0Ruti0JqsKtgWyntZpv2GenuOUH16SRr6TC9+5pLngE289XVIQHY2op1Gl78FaFVNkgEbbs9uTOdl++vnUWY+UHINiA1HEbS08FE/JZIIeuJFO4FbWZZkiyzr04T9rxeyGOTnMo9QhIxnc+IWXVqXS+XUJM+3PDhf2jzXvgf7KQ2ZfK4vS70WDBtwhuoiH2hVZH1bGnHgrXysFPYrfDfBwMOZfs+AtUHvN4evxR/syFLuW2zolCtM=
  on:
    tags: true
    repo: giswqs/lidar_dem
    python: 3.6
